### ISSUE TITLE
Type Conversion Problem with IAR

### ISSUE THREAD

**Issue by martin-mm** [ErichStyger/McuOnEclipse_PEx#28] opened 2017-05-13 16:52 UTC
Hi Erich,

I found some other problems with type conversion using IAR and PE.
My Setup: Eclipse - Neon, IAR V8.0, PE V3.0.2, newest MCUonECLIPSE components (2017-05-06) and patches for DS18B20, FSL_USB_Stack_11.05.2017 and OneWire_10.05.2017

I use a CLS component for the console. In

unsigned CLS1_printfIO(CLS1_ConstStdIOType *io, const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS1_printfPutChar, io->stdOut, fmt, args);
  va_end(args);
  return count;
}

the compiler complaines about passing the wrong pointer argument

can be fixed by using a cast:

  count = XF1_xvformat(CLS1_printfPutChar, (void *)(io->stdOut), fmt, args);

same for

unsigned CLS1_printf(const char *fmt, ...)
{
  va_list args;
  unsigned int count = 0;

  va_start(args,fmt);
  count = XF1_xvformat(CLS1_printfPutChar, CLS1_GetStdio()->stdOut, fmt, args);
  va_end(args);
  return count;
}

->

  count = XF1_xvformat(CLS1_printfPutChar, (void *)(CLS1_GetStdio()->stdOut), fmt, args);

Best regards

Martin

**Comment by martin-mm** [comment] 2017-05-13 18:15
Sorry - I trapped into version confusion with Eclipse. Problem should be already fixed since an older issue posted by me is already closed. Installing PE 3.0.0 + Update 3.0.2 and the the new MCUonECLIPSE updates (via Processor Expert Import Components) seems to lead to more than one repository and older components are used. Haven't that yet running yet.

**Comment by ErichStyger** [comment] 2017-05-14 17:58
Hi Martin,
are you saying that the issue is not valid any more and can be closed?

Thanks,
Erich

**Comment by martin-mm** [comment] 2017-05-15 05:58
Hi Erich,

 

Yes – I had a problem that the new installation did additionally use an old repository and took the source for generating the drivers from there.

 

By the way – with MCUXpresso after merging Freescale with NXP, will we have to expect the next merger with SnapDragon processors now 😊

 

Best regards

 

Martin

**Comment by ErichStyger** [comment] 2017-05-15 06:19
Ok, thanks for confirmation, closing issue now.

**Closed by ErichStyger** 2017-05-15 06:19 UTC
